# Generated by Django 2.2.6 on 2019-10-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Dependents', models.CharField(choices=[('1', '1'), ('2', '2'), ('3+', '3+')], max_length=2)),
                ('Education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=20)),
                ('Self_Employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Income', models.IntegerField()),
                ('Coapplicant_Income', models.IntegerField()),
                ('LoanAmount', models.IntegerField()),
                ('Loan_Amount_Term', models.IntegerField()),
                ('Credit_History', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=10)),
                ('Property_Area', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
            ],
        ),
    ]
