# Generated by Django 2.2.6 on 2019-10-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapproval',
            old_name='Coapplicant_Income',
            new_name='ApplicantIncome',
        ),
        migrations.RenameField(
            model_name='loanapproval',
            old_name='Income',
            new_name='CoapplicantIncome',
        ),
    ]
