# Generated by Django 2.2.6 on 2019-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0003_auto_20191005_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapproval',
            name='Married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
            preserve_default=False,
        ),
    ]
