# Generated by Django 2.2.6 on 2019-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0004_loanapproval_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapproval',
            name='Credit_History',
            field=models.FloatField(choices=[('1', 'Yes'), ('0', 'No')]),
        ),
    ]
