# Generated by Django 2.2.4 on 2019-08-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Company', 'verbose_name_plural': 'About Company'},
        ),
    ]
